language: php
php:
- 5.5
- 5.6
install: composer install
script:
- ./vendor/bin/phing test
notifications:
  email:
   recipients:
   - nicolas.leroy@gmail.com
notifications:
  slack: cnet:UzmZZjVck1RNHTyrTSe6NTd9
